version: '3'

services:
  application:
    build: ./docker/php
    image: exercise-symfony4-application
    volumes:
      - ./:/var/www/html:cached
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/php.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application
